FirmRegister/FirmRegister.Web/Areas/Admin/Controllers/AdminController.cs
using FirmRegister.Domain.Models;
using FirmRegister.Domain.Utils;
using FirmRegister.Web.Controllers.Abstract;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Web;
using System.Web.Mvc;

namespace FirmRegister.Web.Areas.Admin.Controllers
{
    [Authorize(Roles = "Operator")]
    [RouteArea]
    public partial class AdminController : BaseController
    {
        public virtual ActionResult Index(int page = 1)
        {
            var users = this.UserManager.Users
                .ToList()
                .ToPagedList(page, GlobalConstants.PageSize);

            return View(users);
        }

        public virtual ActionResult Edit(string id)
        {
            var user = this.UserManager.FindById(id);

            return View(user);
        }

        [HttpPost]
        public virtual ActionResult Edit(ApplicationUser editedUser, HttpPostedFileBase image = null)
        {
            var user = this.UserManager.FindById(editedUser.Id);

            if (image != null)
            {
                user.ImageMimeType = image.ContentType;
                user.ImageData = new byte[image.ContentLength];
                image.InputStream.Read(user.ImageData, 0,
                image.ContentLength);
            }

            user.LastName = editedUser.LastName;
            user.FirstName = editedUser.FirstName;
            user.Age = editedUser.Age;
            user.Email = editedUser.Email;

            this.UserManager.Update(user);

            return RedirectToAction("Index");

        }
        
        public virtual ActionResult Delete(string id)
        {
            var user = this.UserManager.FindById(id);

            this.UserManager.Delete(user);

            return RedirectToAction("Index");
        }

        public ActionResult MakeAdmin(string id)
        {
            this.UserManager.AddToRole(id, GlobalConstants.OperatorRole);

            return RedirectToAction("Index");
        }

        public ActionResult Unadmin(string id)
        {
            this.UserManager.RemoveFromRole(id, GlobalConstants.OperatorRole);

            return RedirectToAction("Index");
        }
    }
}

FirmRegister/FirmRegister.Web/Controllers/EmployeeController.cs
using FirmRegister.Domain.Models;
using FirmRegister.Web.Controllers.Abstract;
using Microsoft.AspNet.Identity;
using System.Web;
using System.Web.Mvc;

namespace FirmRegister.Web.Controllers
{
    public class EmployeeController : BaseController
    {
        public ActionResult Details(string id)
        {
            var user = this.UserManager.FindById(id);

            return View(user);
        }

        public FileContentResult GetImage(string id)
        {
            var user = this.UserManager.FindById(id);

            if (user != null)
            {
                return File(user.ImageData, user.ImageMimeType);
            }
            else
            {
                return null;
            }
        }

        public ActionResult Edit()
        {
            var user = this.CurrentUser;

            return View(user);
        }

        [HttpPost]
        public virtual ActionResult Edit(ApplicationUser editedUser, HttpPostedFileBase image = null)
        {
            if (image != null)
            {
                this.CurrentUser.ImageMimeType = image.ContentType;
                this.CurrentUser.ImageData = new byte[image.ContentLength];
                image.InputStream.Read(this.CurrentUser.ImageData, 0,
                image.ContentLength);
            }

            this.CurrentUser.LastName = editedUser.LastName;
            this.CurrentUser.FirstName = editedUser.FirstName;
            this.CurrentUser.Age = editedUser.Age;
            this.CurrentUser.Email = editedUser.Email;

            this.UserManager.Update(this.CurrentUser);

            return RedirectToAction("Details", new { id = this.CurrentUser.Id });
        }
    }
}

FirmRegister/FirmRegister.Web/Areas/Admin/Views/Admin/Edit.cshtml
@model FirmRegister.Domain.Models.ApplicationUser

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm("Edit", "Admin", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        <h4>Edit user</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>



        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Age, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Age, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Age, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div style="position:relative;">
                <label>Image</label>
                <a class='btn' href='javascript:;'>
                    Choose File...
                    <input type="file" name="Image" size="40"
                           style="position:absolute;z-index:2;top:0;left:0;filter: alpha(opacity=0); opacity:0;background-color:transparent;color:transparent;" onchange='$("#upload-fileinfo").html($(this).val());'>
                </a>
                <span class='label label-info' id="upload-file-info">
                </span>
            </div>
            @if (Model.ImageData == null)
            {
                <div class="form-control-static">
                    No Image
                </div>
            }
            else
            {
                <img class="img-thumbnail" width="150" height="150" src="@Url.Action("GetImage", "Employee",new { id=Model.Id })" />
            }
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

FirmRegister/FirmRegister.Web/Areas/Admin/Views/Admin/Index.cshtml
@using PagedList;
@using PagedList.Mvc;

@using Microsoft.AspNet.Identity
@using Microsoft.AspNet.Identity.Owin;
@model IPagedList<FirmRegister.Domain.Models.ApplicationUser>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<table class="table">
    <tr>
        <th>
            Email
        </th>

        <th>
            Age
        </th>
        <th>
            First Name
        </th>
        <th>
            LastName
        </th>
        <th>
            Gender
        </th>
        <th>Is operator</th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        var manager = this.Request.GetOwinContext().GetUserManager<ApplicationUserManager>();
        var isAdmin = manager.GetRoles(item.Id).Contains(FirmRegister.Domain.Utils.GlobalConstants.OperatorRole);

        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Age)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Gender)
            </td>
            <td>
                @if (isAdmin)
                {
                    @:Yes

                }
                else
                {
                    @:No
                }
            </td>
            <td>
                @if (isAdmin)
                {
                    @Html.ActionLink("Remove Operator", "Unadmin", new { id = item.Id }) @:|

                }
                else
                {
                    @Html.ActionLink("Make Operator", "MakeAdmin", new { id = item.Id }) @:|
                }

                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Details", "Details", new { id = item.Id, area = "", controller = "Employee" }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
    }

</table>
<br />

Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("Index",
    new { page = page }))